#基本配置
server:
  port: 8080
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/, classpath:/templates/, classpath:/xmgxh/
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: cn.svenbarnett.dframe.domain


# shiro Filter 路由
shiroFilter:
  loginUrl: frame/login/login
  successUrl: frame/main/index
  unauthorizedUrl: frame/main/unauthorized
