# 开发环境配置
logging:
  level.root: info
  level:
    cn.svenbarnett.dframe: debug
    tk.mybatis.mapper: debug
  path: logs/
  file: dframe-web.log
spring:
  datasource:
    username: root
    password: root12345
    url: jdbc:mysql://127.0.0.1:3306/dframe?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
server:
  servlet:
    context-path: /dframe
nasshare: /Users/svenbarnett/Downloads/nasshare/temp/

